apiVersion: v1
kind: Namespace
metadata: 
  name: spark
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: driver-pod-sa
  namespace: spark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: driver-pod-rb
  namespace: spark
subjects:
- kind: ServiceAccount
  name: driver-pod-sa
  namespace: spark
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-driver-sa
  namespace: spark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-driver-rb
  namespace: spark
subjects:
- kind: ServiceAccount
  name: spark-driver-sa
  namespace: spark
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
